set_property SRC_FILE_INFO {cfile:H:/Users/Pravindu/Xilinx/UART_Module/UARTTop/UARTTop.srcs/constrs_1/new/UARTLoopBackConstr.xdc rfile:../../../UARTTop.srcs/constrs_1/new/UARTLoopBackConstr.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports CLK]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports RESET]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports TX]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B18 [get_ports RX]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK] -min -add_delay 0.000 [get_ports {TX}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks CLK] -min -add_delay 0.000 [get_ports {RX}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks CLK] -max -add_delay 0.000 [get_ports {TX}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock [get_clocks CLK] -max -add_delay 0.000 [get_ports {RX}]
